### ISSUE TITLE
Crash on Android 9.0

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#204]
```
java.lang.NoClassDefFoundError: 
  at gw.b (com.google.android.gms.dynamite_mapsdynamite@17785083@17.7.85 (100408-253824076):3)
  at gt.a (com.google.android.gms.dynamite_mapsdynamite@17785083@17.7.85 (100408-253824076):3)
  at gv.a (com.google.android.gms.dynamite_mapsdynamite@17785083@17.7.85 (100408-253824076):14)
  at com.google.maps.api.android.lib6.drd.ak.a (com.google.android.gms.dynamite_mapsdynamite@17785083@17.7.85 (100408-253824076):6)
  at fx.a (com.google.android.gms.dynamite_mapsdynamite@17785083@17.7.85 (100408-253824076):22)
  at fx.run (com.google.android.gms.dynamite_mapsdynamite@17785083@17.7.85 (100408-253824076):8)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:134)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at ab.loadClass (com.google.android.gms.dynamite_dynamiteloader@17785083@17.7.85 (100408-253824076):4)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
```

Introduced since #199

Seems related to [this](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library)

I think we need to upgrade `com.google.android.gms:play-services-maps` to at least `16.1.0`

**Comment by alexsegura** [comment]
Should be fixed in 479f0983257b09c01dcbc942594a7a734017f4b8
